#!/bin/sh /etc/rc.common
# Copyright (C) 2007 OpenWrt.org


START=90
STOP=95
USE_PROCD=1

start_service() {
        procd_open_instance
        procd_set_param command /usr/sbin/zio_garp


}

service_triggers()
{
        procd_add_reload_trigger "garp"
}

